version: '3.7'

networks:
  default:
    external:
      name: dev-base

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
