version: '3.7'

networks:
  default:
    external:
      name: dev-base

services:
  mysql:
    image: mysql:5.6
    container_name: dev-base-mysql
    ports:
      - "3306:3306"
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    container_name: dev-base-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql

  portainer:
    image: portainer/portainer
    container_name: dev-base-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.1
    container_name: dev-base-logstash
    ports: ['9600:9600']
    depends_on: ['elasticsearch']
    volumes:
      - './etc/logstash/pipeline:/usr/share/logstash/pipeline'
      - './var/logs:/logs'

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.1
    container_name: dev-base-filebeat
    user: root
    volumes:
      - './var/filebeat/log/:/var/log/:ro'
      - './var/filebeat/docker.sock:/var/run/docker.sock'
      - './var/logs/:/var/lib/docker/containers/logs:ro'
#      - './etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    command: ["--strict.perms=false"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - 'elasticsearch'
